import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const id = () => integer("id").primaryKey({ autoIncrement: true });
const active = () => integer("active", { mode: "boolean" }).notNull().default(true);
const created = (name = "created_at") => text(name).notNull().default("CURRENT_TIMESTAMP");

export const priceLists = sqliteTable("price_lists", { id:id(), code:text("code").notNull(), name:text("name").notNull(), priceModifier:real("price_modifier").notNull().default(1), isDefault:integer("is_default", { mode: "boolean" }).notNull().default(false), active:active(), createdAt:created() }, t=>[uniqueIndex("price_lists_code_uq").on(t.code),uniqueIndex("price_lists_name_uq").on(t.name)]);
export const clients = sqliteTable("clients", { id:id(), code:text("code").notNull(), name:text("name").notNull(), phone:text("phone"), email:text("email"), address:text("address"), priceListId:integer("price_list_id").references(()=>priceLists.id), active:active(), createdAt:created() }, t=>[uniqueIndex("clients_code_uq").on(t.code),uniqueIndex("clients_name_uq").on(t.name)]);
export const suppliers = sqliteTable("suppliers", { id:id(), code:text("code").notNull(), name:text("name").notNull(), phone:text("phone"), email:text("email"), address:text("address"), active:active(), createdAt:created() }, t=>[uniqueIndex("suppliers_code_uq").on(t.code),uniqueIndex("suppliers_name_uq").on(t.name)]);
export const categories = sqliteTable("categories", { id:id(), code:text("code").notNull(), name:text("name").notNull(), prefix:text("prefix"), kind:text("kind").notNull(), active:active() }, t=>[uniqueIndex("categories_code_uq").on(t.code),uniqueIndex("categories_name_uq").on(t.name),uniqueIndex("categories_prefix_uq").on(t.prefix)]);
export const codeBase = sqliteTable("code_base", { id:id(), code:text("code").notNull(), name:text("name").notNull(), entityType:text("entity_type").notNull(), categoryId:integer("category_id").references(()=>categories.id), manualCategory:text("manual_category"), manualType:text("manual_type"), description:text("description"), unit:text("unit"), active:active(), createdAt:created() }, t=>[uniqueIndex("code_base_code_uq").on(t.code),uniqueIndex("code_base_name_uq").on(t.name)]);
export const rawMaterials = sqliteTable("raw_materials", { id:id(), codeBaseId:integer("code_base_id").notNull().references(()=>codeBase.id), categoryId:integer("category_id").references(()=>categories.id), preferredSupplierId:integer("preferred_supplier_id").references(()=>suppliers.id), unit:text("unit").notNull(), currentStock:real("current_stock").notNull().default(0), minimumStock:real("minimum_stock").notNull().default(0), currentCostCents:integer("current_cost_cents").notNull().default(0), notes:text("notes"), active:active() });
export const rawMaterialPurchases = sqliteTable("raw_material_purchases", { id:id(), operationKey:text("operation_key").notNull().unique(), materialId:integer("material_id").notNull().references(()=>rawMaterials.id), supplierId:integer("supplier_id").references(()=>suppliers.id), quantity:real("quantity").notNull(), inputQuantity:real("input_quantity"), inputUnit:text("input_unit"), baseQuantity:real("base_quantity"), totalCostCents:integer("total_cost_cents").notNull(), unitCostCents:integer("unit_cost_cents").notNull(), paymentStatus:text("payment_status").notNull().default("PAID"), invoiceNumber:text("invoice_number"), purchasedUnit:text("purchased_unit"), status:text("status").notNull().default("CONFIRMED"), cancelledAt:text("cancelled_at"), purchasedAt:created("purchased_at"), notes:text("notes") });
export const products = sqliteTable("products", { id:id(), codeBaseId:integer("code_base_id").notNull().references(()=>codeBase.id), categoryId:integer("category_id").references(()=>categories.id), type:text("type").notNull(), photoUrl:text("photo_url"), salePriceCents:integer("sale_price_cents").notNull().default(0), estimatedCostCents:integer("estimated_cost_cents").notNull().default(0), lastBatchUnitCostCents:integer("last_batch_unit_cost_cents").notNull().default(0), profitPercentage:real("profit_percentage").notNull().default(30), suggestedPriceCents:integer("suggested_price_cents").notNull().default(0), pricingMode:text("pricing_mode").notNull().default("manual_price"), targetMarginPercentage:real("target_margin_percentage"), currentStock:real("current_stock").notNull().default(0), minimumStock:real("minimum_stock").notNull().default(0), active:active() });
export const priceListItems = sqliteTable("price_list_items", { id:id(), priceListId:integer("price_list_id").notNull().references(()=>priceLists.id), productId:integer("product_id").notNull().references(()=>products.id), priceCents:integer("price_cents").notNull(), createdAt:created() }, t=>[uniqueIndex("price_list_items_list_product_uq").on(t.priceListId,t.productId)]);
export const recipes = sqliteTable("recipes", { id:id(), productId:integer("product_id").notNull().references(()=>products.id).unique(), yieldQuantity:real("yield_quantity").notNull().default(1), active:active(), updatedAt:text("updated_at") });
export const recipeItems = sqliteTable("recipe_items", { id:id(), recipeId:integer("recipe_id").notNull().references(()=>recipes.id), materialId:integer("material_id").notNull().references(()=>rawMaterials.id), quantityPerYield:real("quantity_per_yield").notNull() });
export const combos = sqliteTable("combos", { id:id(), productId:integer("product_id").notNull().references(()=>products.id).unique(), active:active(), updatedAt:text("updated_at") });
export const comboRecipeItems = sqliteTable("combo_recipe_items", { id:id(), comboId:integer("combo_id").notNull().references(()=>combos.id), componentProductId:integer("component_product_id").notNull().references(()=>products.id), quantity:real("quantity").notNull() });
export const comboMaterialItems = sqliteTable("combo_material_items", { id:id(), comboId:integer("combo_id").notNull().references(()=>combos.id), materialId:integer("material_id").notNull().references(()=>rawMaterials.id), quantity:real("quantity").notNull() }, t=>[uniqueIndex("combo_material_items_combo_material_uq").on(t.comboId,t.materialId)]);
export const mixtures = sqliteTable("mixtures", { id:id(), code:text("code").notNull(), name:text("name").notNull(), unit:text("unit").notNull().default("ml"), yieldQuantity:real("yield_quantity").notNull().default(1), minimumStock:real("minimum_stock").notNull().default(0), active:active(), notes:text("notes"), createdAt:created(), updatedAt:text("updated_at").notNull().default("CURRENT_TIMESTAMP") }, t=>[uniqueIndex("mixtures_code_uq").on(t.code), uniqueIndex("mixtures_name_uq").on(t.name)]);
export const mixtureFormulaItems = sqliteTable("mixture_formula_items", { id:id(), mixtureId:integer("mixture_id").notNull().references(()=>mixtures.id), materialId:integer("material_id").notNull().references(()=>rawMaterials.id), quantityPerYield:real("quantity_per_yield").notNull(), createdAt:created() }, t=>[uniqueIndex("mixture_formula_items_mixture_material_uq").on(t.mixtureId,t.materialId)]);
export const recipeMixtureItems = sqliteTable("recipe_mixture_items", { id:id(), recipeId:integer("recipe_id").notNull().references(()=>recipes.id), mixtureId:integer("mixture_id").notNull().references(()=>mixtures.id), quantityPerYield:real("quantity_per_yield").notNull(), createdAt:created() }, t=>[uniqueIndex("recipe_mixture_items_recipe_mixture_uq").on(t.recipeId,t.mixtureId)]);
export const mixturePreparations = sqliteTable("mixture_preparations", { id:id(), operationKey:text("operation_key").notNull().unique(), mixtureId:integer("mixture_id").notNull().references(()=>mixtures.id), theoreticalQuantity:real("theoretical_quantity").notNull(), actualQuantity:real("actual_quantity").notNull(), wasteQuantity:real("waste_quantity").notNull().default(0), wastePercentage:real("waste_percentage").notNull().default(0), totalCostCents:integer("total_cost_cents").notNull().default(0), unitCostCents:integer("unit_cost_cents").notNull().default(0), preparedAt:created("prepared_at"), status:text("status").notNull().default("CONFIRMED"), cancelledAt:text("cancelled_at"), notes:text("notes"), createdAt:created(), updatedAt:text("updated_at").notNull().default("CURRENT_TIMESTAMP") });
export const mixturePreparationMaterials = sqliteTable("mixture_preparation_materials", { id:id(), preparationId:integer("preparation_id").notNull().references(()=>mixturePreparations.id), materialId:integer("material_id").notNull().references(()=>rawMaterials.id), quantityUsed:real("quantity_used").notNull(), frozenUnitCostCents:integer("frozen_unit_cost_cents").notNull().default(0), frozenTotalCostCents:integer("frozen_total_cost_cents").notNull().default(0) }, t=>[uniqueIndex("mixture_preparation_materials_preparation_material_uq").on(t.preparationId,t.materialId)]);
export const mixtureLots = sqliteTable("mixture_lots", { id:id(), preparationId:integer("preparation_id").notNull().references(()=>mixturePreparations.id), mixtureId:integer("mixture_id").notNull().references(()=>mixtures.id), lotNumber:text("lot_number").notNull(), initialQuantity:real("initial_quantity").notNull(), availableQuantity:real("available_quantity").notNull(), totalCostCents:integer("total_cost_cents").notNull().default(0), unitCostCents:integer("unit_cost_cents").notNull().default(0), preparedAt:created("prepared_at"), status:text("status").notNull().default("ACTIVE"), cancelledAt:text("cancelled_at"), notes:text("notes"), createdAt:created(), updatedAt:text("updated_at").notNull().default("CURRENT_TIMESTAMP") }, t=>[uniqueIndex("mixture_lots_preparation_uq").on(t.preparationId), uniqueIndex("mixture_lots_lot_number_uq").on(t.lotNumber)]);
export const mixtureMovements = sqliteTable("mixture_movements", { id:id(), operationKey:text("operation_key").notNull(), mixtureId:integer("mixture_id").notNull().references(()=>mixtures.id), lotId:integer("lot_id").notNull().references(()=>mixtureLots.id), movementType:text("movement_type").notNull(), quantityDelta:real("quantity_delta").notNull(), balanceAfter:real("balance_after").notNull(), unitCostCents:integer("unit_cost_cents").notNull().default(0), referenceTable:text("reference_table").notNull(), referenceId:integer("reference_id").notNull(), notes:text("notes"), reversedMovementId:integer("reversed_movement_id"), createdAt:created() });
export const mixtureLotConsumptions = sqliteTable("mixture_lot_consumptions", { id:id(), lotId:integer("lot_id").notNull().references(()=>mixtureLots.id), operationKey:text("operation_key").notNull(), referenceTable:text("reference_table").notNull(), referenceId:integer("reference_id").notNull(), quantity:real("quantity").notNull(), frozenUnitCostCents:integer("frozen_unit_cost_cents").notNull().default(0), frozenTotalCostCents:integer("frozen_total_cost_cents").notNull().default(0), createdAt:created() });
export const manufacturingBatches = sqliteTable("manufacturing_batches", { id:id(), operationKey:text("operation_key").notNull().unique(), batchNumber:text("batch_number"), productId:integer("product_id").notNull().references(()=>products.id), quantity:real("quantity").notNull(), initialQuantity:real("initial_quantity"), availableQuantity:real("available_quantity"), totalCostCents:integer("total_cost_cents").notNull(), unitCostCents:integer("unit_cost_cents").notNull(), manufacturedAt:created("manufactured_at"), notes:text("notes") });
export const manufacturingMaterials = sqliteTable("manufacturing_materials", { id:id(), batchId:integer("batch_id").notNull().references(()=>manufacturingBatches.id), materialId:integer("material_id").notNull().references(()=>rawMaterials.id), quantityUsed:real("quantity_used").notNull(), frozenUnitCostCents:integer("frozen_unit_cost_cents").notNull(), frozenTotalCostCents:integer("frozen_total_cost_cents").notNull() });
export const comboBatches = sqliteTable("combo_batches", { id:id(), operationKey:text("operation_key").notNull().unique(), batchNumber:text("batch_number"), comboId:integer("combo_id").notNull().references(()=>combos.id), quantity:real("quantity").notNull(), initialQuantity:real("initial_quantity"), availableQuantity:real("available_quantity"), totalCostCents:integer("total_cost_cents").notNull(), unitCostCents:integer("unit_cost_cents").notNull(), assembledAt:created("assembled_at"), notes:text("notes") });
export const comboBatchItems = sqliteTable("combo_batch_items", { id:id(), batchId:integer("batch_id").notNull().references(()=>comboBatches.id), componentProductId:integer("component_product_id").notNull().references(()=>products.id), quantityUsed:real("quantity_used").notNull(), frozenUnitCostCents:integer("frozen_unit_cost_cents").notNull(), frozenTotalCostCents:integer("frozen_total_cost_cents").notNull() });
export const comboBatchItemLotAllocations = sqliteTable("combo_batch_item_lot_allocations", { id:id(), comboBatchItemId:integer("combo_batch_item_id").notNull().references(()=>comboBatchItems.id), manufacturingBatchId:integer("manufacturing_batch_id").references(()=>manufacturingBatches.id), sourceComboBatchId:integer("source_combo_batch_id").references(()=>comboBatches.id), quantity:real("quantity").notNull(), frozenUnitCostCents:integer("frozen_unit_cost_cents").notNull(), frozenTotalCostCents:integer("frozen_total_cost_cents").notNull() });
export const comboBatchMaterials = sqliteTable("combo_batch_materials", { id:id(), batchId:integer("batch_id").notNull().references(()=>comboBatches.id), materialId:integer("material_id").notNull().references(()=>rawMaterials.id), quantityUsed:real("quantity_used").notNull(), frozenUnitCostCents:integer("frozen_unit_cost_cents").notNull(), frozenTotalCostCents:integer("frozen_total_cost_cents").notNull() });
export const sales = sqliteTable("sales", { id:id(), operationKey:text("operation_key").notNull().unique(), clientId:integer("client_id").references(()=>clients.id), totalCents:integer("total_cents").notNull(), totalCostCents:integer("total_cost_cents").notNull(), profitCents:integer("profit_cents").notNull(), status:text("status").notNull().default("PAID"), paymentStatus:text("payment_status").notNull().default("PENDING"), origin:text("origin").notNull().default("DIRECT"), soldAt:created("sold_at"), notes:text("notes") });
export const saleItems = sqliteTable("sale_items", { id:id(), saleId:integer("sale_id").notNull().references(()=>sales.id), productId:integer("product_id").notNull().references(()=>products.id), sourceOrderItemId:integer("source_order_item_id"), quantity:real("quantity").notNull(), frozenUnitPriceCents:integer("frozen_unit_price_cents").notNull(), frozenUnitCostCents:integer("frozen_unit_cost_cents").notNull(), lineTotalCents:integer("line_total_cents").notNull(), lineCostCents:integer("line_cost_cents").notNull() });
export const saleManualItems = sqliteTable("sale_manual_items", { id:id(), saleId:integer("sale_id").notNull().references(()=>sales.id), description:text("description").notNull(), quantity:real("quantity").notNull(), frozenUnitPriceCents:integer("frozen_unit_price_cents").notNull(), lineTotalCents:integer("line_total_cents").notNull(), notes:text("notes") });
export const finishedStockAllocations = sqliteTable("finished_stock_allocations", { id:id(), saleItemId:integer("sale_item_id").notNull().references(()=>saleItems.id), manufacturingBatchId:integer("manufacturing_batch_id").references(()=>manufacturingBatches.id), comboBatchId:integer("combo_batch_id").references(()=>comboBatches.id), quantity:real("quantity").notNull(), frozenUnitCostCents:integer("frozen_unit_cost_cents").notNull(), frozenTotalCostCents:integer("frozen_total_cost_cents").notNull(), createdAt:created() });
export const expenses = sqliteTable("expenses", { id:id(), code:text("code").notNull().unique(), categoryId:integer("category_id").references(()=>categories.id), codeBaseId:integer("code_base_id").references(()=>codeBase.id), supplierId:integer("supplier_id").references(()=>suppliers.id), description:text("description").notNull(), quantity:real("quantity"), unitCostCents:integer("unit_cost_cents"), amountCents:integer("amount_cents").notNull(), paymentStatus:text("payment_status").notNull().default("PAID"), recordStatus:text("record_status").notNull().default("CONFIRMED"), invoiceNumber:text("invoice_number"), rawMaterialPurchaseId:integer("raw_material_purchase_id").references(()=>rawMaterialPurchases.id), incurredAt:created("incurred_at"), notes:text("notes") });
export const materialSaleItems = sqliteTable("material_sale_items", { id:id(), saleId:integer("sale_id").notNull().references(()=>sales.id), materialId:integer("material_id").notNull().references(()=>rawMaterials.id), quantity:real("quantity").notNull(), frozenUnitPriceCents:integer("frozen_unit_price_cents").notNull(), frozenUnitCostCents:integer("frozen_unit_cost_cents").notNull(), lineTotalCents:integer("line_total_cents").notNull(), lineCostCents:integer("line_cost_cents").notNull() });
export const stockMovements = sqliteTable("stock_movements", { id:id(), operationKey:text("operation_key").notNull(), entityType:text("entity_type").notNull(), materialId:integer("material_id").references(()=>rawMaterials.id), productId:integer("product_id").references(()=>products.id), movementType:text("movement_type").notNull(), quantityDelta:real("quantity_delta").notNull(), balanceAfter:real("balance_after").notNull(), unitCostCents:integer("unit_cost_cents").notNull().default(0), referenceTable:text("reference_table").notNull(), referenceId:integer("reference_id").notNull(), notes:text("notes"), reversedMovementId:integer("reversed_movement_id"), createdAt:created() });
export const monthlyProfits = sqliteTable("monthly_profits", { id:id(), month:text("month").notNull().unique(), salesCents:integer("sales_cents").notNull().default(0), productCostCents:integer("product_cost_cents").notNull().default(0), expenseCents:integer("expense_cents").notNull().default(0), profitCents:integer("profit_cents").notNull().default(0), calculatedAt:created("calculated_at") });
export const profitHistory = sqliteTable("profit_history", { id:id(), month:text("month").notNull(), salesCents:integer("sales_cents").notNull(), productCostCents:integer("product_cost_cents").notNull(), expenseCents:integer("expense_cents").notNull(), profitCents:integer("profit_cents").notNull(), capturedAt:created("captured_at"), reason:text("reason").notNull() });

// Flujo comercial: pedido → pago/venta → envío → remito.
export const orders = sqliteTable("orders", { id:id(), number:text("number").notNull().unique(), clientId:integer("client_id").references(()=>clients.id), status:text("status").notNull().default("NEW"), paymentStatus:text("payment_status").notNull().default("PENDING"), subtotalCents:integer("subtotal_cents").notNull().default(0), discountCents:integer("discount_cents").notNull().default(0), shippingCents:integer("shipping_cents").notNull().default(0), totalCents:integer("total_cents").notNull().default(0), expectedAt:text("expected_at"), deliveryAddress:text("delivery_address"), notes:text("notes"), internalNotes:text("internal_notes"), saleId:integer("sale_id").references(()=>sales.id), confirmedAt:text("confirmed_at"), stockConsumedAt:text("stock_consumed_at"), cancelledAt:text("cancelled_at"), createdAt:created(), updatedAt:text("updated_at").notNull().default("CURRENT_TIMESTAMP"), archivedAt:text("archived_at") });
export const orderItems = sqliteTable("order_items", { id:id(), orderId:integer("order_id").notNull().references(()=>orders.id), productId:integer("product_id").references(()=>products.id), description:text("description").notNull(), customization:text("customization"), quantity:real("quantity").notNull(), unitPriceCents:integer("unit_price_cents").notNull(), lineTotalCents:integer("line_total_cents").notNull(), requiresManufacturing:integer("requires_manufacturing",{mode:"boolean"}).notNull().default(false) });
export const payments = sqliteTable("payments", { id:id(), orderId:integer("order_id").references(()=>orders.id), saleId:integer("sale_id").references(()=>sales.id), direction:text("direction").notNull().default("IN"), method:text("method").notNull(), amountCents:integer("amount_cents").notNull(), status:text("status").notNull().default("CONFIRMED"), paidAt:created("paid_at"), reference:text("reference"), notes:text("notes"), cancelledAt:text("cancelled_at") });
export const shipments = sqliteTable("shipments", { id:id(), orderId:integer("order_id").notNull().references(()=>orders.id), clientId:integer("client_id").references(()=>clients.id), status:text("status").notNull().default("PENDING"), address:text("address").notNull(), carrier:text("carrier"), trackingCode:text("tracking_code"), costCents:integer("cost_cents").notNull().default(0), dispatchedAt:text("dispatched_at"), deliveredAt:text("delivered_at"), notes:text("notes"), createdAt:created(), updatedAt:text("updated_at").notNull().default("CURRENT_TIMESTAMP") });
export const deliveryNotes = sqliteTable("delivery_notes", { id:id(), number:text("number").notNull().unique(), orderId:integer("order_id").references(()=>orders.id), saleId:integer("sale_id").references(()=>sales.id), clientId:integer("client_id").references(()=>clients.id), issuedAt:created("issued_at"), status:text("status").notNull().default("ISSUED"), snapshotJson:text("snapshot_json").notNull(), fileKey:text("file_key"), cancelledAt:text("cancelled_at") });
export const saleDocuments = sqliteTable("sale_documents", { id:id(), saleId:integer("sale_id").notNull().references(()=>sales.id), orderId:integer("order_id").references(()=>orders.id), type:text("type").notNull(), storageKey:text("storage_key").notNull().unique(), filename:text("filename").notNull(), version:integer("version").notNull().default(1), status:text("status").notNull().default("PENDING"), snapshotJson:text("snapshot_json"), pdfBase64:text("pdf_base64"), errorMessage:text("error_message"), generatedBy:text("generated_by"), createdAt:created(), generatedAt:text("generated_at") });

// Compras con múltiples renglones. Las compras históricas unitarias se conservan.
export const purchaseOrders = sqliteTable("purchase_orders", { id:id(), number:text("number").notNull().unique(), supplierId:integer("supplier_id").references(()=>suppliers.id), status:text("status").notNull().default("DRAFT"), paymentStatus:text("payment_status").notNull().default("PENDING"), totalCents:integer("total_cents").notNull().default(0), invoiceNumber:text("invoice_number"), purchasedAt:created("purchased_at"), notes:text("notes"), cancelledAt:text("cancelled_at"), createdAt:created() });
export const purchaseOrderItems = sqliteTable("purchase_order_items", { id:id(), purchaseOrderId:integer("purchase_order_id").notNull().references(()=>purchaseOrders.id), materialId:integer("material_id").notNull().references(()=>rawMaterials.id), quantity:real("quantity").notNull(), unit:text("unit").notNull(), unitCostCents:integer("unit_cost_cents").notNull(), lineTotalCents:integer("line_total_cents").notNull() });

// Auditoría y preferencias. Los eventos financieros o de stock no se eliminan.
export const auditLogs = sqliteTable("audit_logs", { id:id(), action:text("action").notNull(), entityType:text("entity_type").notNull(), entityId:integer("entity_id"), actorEmail:text("actor_email"), summary:text("summary").notNull(), beforeJson:text("before_json"), afterJson:text("after_json"), createdAt:created() });
export const appSettings = sqliteTable("app_settings", { key:text("key").primaryKey(), valueJson:text("value_json").notNull(), updatedAt:text("updated_at").notNull().default("CURRENT_TIMESTAMP") });
