BEGIN;

CREATE TABLE IF NOT EXISTS public.sensory_options (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL CHECK (kind IN ('FAMILY', 'NOTE', 'SENSATION', 'INTENSITY', 'ROOM', 'MOMENT')),
  slug text NOT NULL CHECK (slug = lower(slug) AND slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  label text NOT NULL CHECK (btrim(label) <> ''),
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (kind, slug),
  UNIQUE (id, kind)
);

CREATE TABLE IF NOT EXISTS public.product_sensory_options (
  product_id integer NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  option_id integer NOT NULL,
  kind text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (product_id, option_id),
  FOREIGN KEY (option_id, kind)
    REFERENCES public.sensory_options(id, kind)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS sensory_options_catalog_idx
  ON public.sensory_options(kind, active, sort_order, label);
CREATE INDEX IF NOT EXISTS product_sensory_options_product_idx
  ON public.product_sensory_options(product_id, kind, sort_order);
CREATE INDEX IF NOT EXISTS product_sensory_options_option_idx
  ON public.product_sensory_options(option_id, product_id);
CREATE UNIQUE INDEX IF NOT EXISTS product_sensory_options_single_value_uq
  ON public.product_sensory_options(product_id, kind)
  WHERE kind IN ('INTENSITY', 'MOMENT');

INSERT INTO public.sensory_options(kind, slug, label, sort_order)
VALUES
  ('FAMILY', 'dulce', 'Dulce', 10),
  ('FAMILY', 'fresca', 'Fresca', 20),
  ('FAMILY', 'citrica', 'Cítrica', 30),
  ('FAMILY', 'floral', 'Floral', 40),
  ('FAMILY', 'amaderada', 'Amaderada', 50),
  ('FAMILY', 'especiada', 'Especiada', 60),
  ('FAMILY', 'frutal', 'Frutal', 70),
  ('FAMILY', 'herbal', 'Herbal', 80),
  ('FAMILY', 'ambarada', 'Ambarada', 90),
  ('NOTE', 'vainilla', 'Vainilla', 10),
  ('NOTE', 'ambar', 'Ámbar', 20),
  ('NOTE', 'sandalo', 'Sándalo', 30),
  ('NOTE', 'lavanda', 'Lavanda', 40),
  ('NOTE', 'jazmin', 'Jazmín', 50),
  ('NOTE', 'limon', 'Limón', 60),
  ('NOTE', 'naranja', 'Naranja', 70),
  ('NOTE', 'bergamota', 'Bergamota', 80),
  ('NOTE', 'rosa', 'Rosa', 90),
  ('NOTE', 'coco', 'Coco', 100),
  ('NOTE', 'canela', 'Canela', 110),
  ('NOTE', 'cedro', 'Cedro', 120),
  ('NOTE', 'eucalipto', 'Eucalipto', 130),
  ('SENSATION', 'relajante', 'Relajante', 10),
  ('SENSATION', 'energizante', 'Energizante', 20),
  ('SENSATION', 'acogedora', 'Acogedora', 30),
  ('SENSATION', 'elegante', 'Elegante', 40),
  ('SENSATION', 'fresca', 'Fresca', 50),
  ('SENSATION', 'sofisticada', 'Sofisticada', 60),
  ('SENSATION', 'calida', 'Cálida', 70),
  ('SENSATION', 'limpia', 'Limpia', 80),
  ('INTENSITY', 'suave', 'Suave', 10),
  ('INTENSITY', 'media', 'Media', 20),
  ('INTENSITY', 'intensa', 'Intensa', 30),
  ('ROOM', 'living', 'Living', 10),
  ('ROOM', 'dormitorio', 'Dormitorio', 20),
  ('ROOM', 'bano', 'Baño', 30),
  ('ROOM', 'cocina', 'Cocina', 40),
  ('ROOM', 'oficina', 'Oficina', 50),
  ('ROOM', 'comedor', 'Comedor', 60),
  ('ROOM', 'espacios-de-relax', 'Espacios de relax', 70),
  ('ROOM', 'local-comercial', 'Local comercial', 80),
  ('MOMENT', 'dia', 'Día', 10),
  ('MOMENT', 'noche', 'Noche', 20),
  ('MOMENT', 'todo-el-dia', 'Todo el día', 30)
ON CONFLICT (kind, slug) DO UPDATE SET
  label = EXCLUDED.label,
  sort_order = EXCLUDED.sort_order,
  active = true,
  updated_at = now();

ALTER TABLE public.sensory_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_sensory_options ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public.sensory_options FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.product_sensory_options FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.sensory_options_id_seq FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.sensory_options TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.product_sensory_options TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.sensory_options_id_seq TO service_role;

COMMENT ON TABLE public.sensory_options IS
  'Catálogo sensorial controlado. RLS default-deny; administración vía servidor KHORA.';
COMMENT ON TABLE public.product_sensory_options IS
  'Relaciones sensoriales de productos. RLS default-deny; sin acceso directo público.';

COMMIT;