-- Mezclas: fórmulas reutilizables de materias primas y lotes trazables.
-- El stock se deriva de los lotes activos; no se duplica en una columna mutable.
create table if not exists public.mixtures (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  unit text not null default 'ml',
  yield_quantity double precision not null default 1 check (yield_quantity > 0),
  minimum_stock double precision not null default 0 check (minimum_stock >= 0),
  active integer not null default 1 check (active in (0, 1)),
  notes text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create table if not exists public.mixture_formula_items (
  id integer generated by default as identity primary key,
  mixture_id integer not null references public.mixtures(id) on delete cascade,
  material_id integer not null references public.raw_materials(id),
  quantity_per_yield double precision not null check (quantity_per_yield > 0),
  created_at text not null default (current_timestamp::text),
  unique (mixture_id, material_id)
);

-- Permite que una receta de producto consuma una mezcla sin alterar recipe_items
-- históricos, que siguen apuntando exclusivamente a materias primas.
create table if not exists public.recipe_mixture_items (
  id integer generated by default as identity primary key,
  recipe_id integer not null references public.recipes(id) on delete cascade,
  mixture_id integer not null references public.mixtures(id),
  quantity_per_yield double precision not null check (quantity_per_yield > 0),
  created_at text not null default (current_timestamp::text),
  unique (recipe_id, mixture_id)
);

create table if not exists public.mixture_preparations (
  id integer generated by default as identity primary key,
  operation_key text not null unique,
  mixture_id integer not null references public.mixtures(id),
  theoretical_quantity double precision not null check (theoretical_quantity > 0),
  actual_quantity double precision not null check (actual_quantity > 0),
  waste_quantity double precision not null default 0 check (waste_quantity >= 0),
  waste_percentage double precision not null default 0 check (waste_percentage >= 0 and waste_percentage <= 100),
  total_cost_cents bigint not null default 0 check (total_cost_cents >= 0),
  unit_cost_cents bigint not null default 0 check (unit_cost_cents >= 0),
  prepared_at text not null default (current_timestamp::text),
  status text not null default 'CONFIRMED' check (status in ('CONFIRMED', 'CANCELLED')),
  cancelled_at text,
  notes text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create table if not exists public.mixture_preparation_materials (
  id integer generated by default as identity primary key,
  preparation_id integer not null references public.mixture_preparations(id) on delete cascade,
  material_id integer not null references public.raw_materials(id),
  quantity_used double precision not null check (quantity_used > 0),
  frozen_unit_cost_cents bigint not null default 0 check (frozen_unit_cost_cents >= 0),
  frozen_total_cost_cents bigint not null default 0 check (frozen_total_cost_cents >= 0),
  unique (preparation_id, material_id)
);

create table if not exists public.mixture_lots (
  id integer generated by default as identity primary key,
  preparation_id integer not null unique references public.mixture_preparations(id),
  mixture_id integer not null references public.mixtures(id),
  lot_number text not null unique,
  initial_quantity double precision not null check (initial_quantity > 0),
  available_quantity double precision not null check (available_quantity >= 0),
  total_cost_cents bigint not null default 0 check (total_cost_cents >= 0),
  unit_cost_cents bigint not null default 0 check (unit_cost_cents >= 0),
  prepared_at text not null default (current_timestamp::text),
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'CANCELLED')),
  cancelled_at text,
  notes text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create table if not exists public.mixture_movements (
  id integer generated by default as identity primary key,
  operation_key text not null,
  mixture_id integer not null references public.mixtures(id),
  lot_id integer not null references public.mixture_lots(id),
  movement_type text not null check (movement_type in ('PREPARATION_OUTPUT', 'CONSUMPTION', 'ADJUSTMENT')),
  quantity_delta double precision not null check (quantity_delta <> 0),
  balance_after double precision not null check (balance_after >= 0),
  unit_cost_cents bigint not null default 0 check (unit_cost_cents >= 0),
  reference_table text not null,
  reference_id integer not null,
  notes text,
  reversed_movement_id integer references public.mixture_movements(id),
  created_at text not null default (current_timestamp::text)
);

create table if not exists public.mixture_lot_consumptions (
  id integer generated by default as identity primary key,
  lot_id integer not null references public.mixture_lots(id),
  operation_key text not null,
  reference_table text not null,
  reference_id integer not null,
  quantity double precision not null check (quantity > 0),
  frozen_unit_cost_cents bigint not null default 0 check (frozen_unit_cost_cents >= 0),
  frozen_total_cost_cents bigint not null default 0 check (frozen_total_cost_cents >= 0),
  created_at text not null default (current_timestamp::text)
);

create index if not exists idx_mixture_formula_items_mixture on public.mixture_formula_items(mixture_id);
create index if not exists idx_mixture_formula_items_material on public.mixture_formula_items(material_id);
create index if not exists idx_recipe_mixture_items_recipe on public.recipe_mixture_items(recipe_id);
create index if not exists idx_mixture_lots_mixture_fifo on public.mixture_lots(mixture_id, prepared_at, id);
create index if not exists idx_mixture_lots_status on public.mixture_lots(status, available_quantity);
create index if not exists idx_mixture_movements_mixture on public.mixture_movements(mixture_id, created_at desc);
create index if not exists idx_mixture_movements_operation on public.mixture_movements(operation_key);
create index if not exists idx_mixture_consumptions_lot on public.mixture_lot_consumptions(lot_id, created_at desc);

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'mixtures', 'mixture_formula_items', 'recipe_mixture_items',
    'mixture_preparations', 'mixture_preparation_materials',
    'mixture_lots', 'mixture_movements', 'mixture_lot_consumptions'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end $$;
