-- KHORA Tienda: publicación, reservas temporales y pedidos públicos.
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS store_published boolean NOT NULL DEFAULT true;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS store_phone_normalized text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS store_source text NOT NULL DEFAULT 'ADMIN';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS store_idempotency_key text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS store_reservation_id bigint;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS store_stock_committed_at timestamptz;
UPDATE public.products SET store_published = true WHERE store_published IS NULL;

CREATE SEQUENCE IF NOT EXISTS public.store_order_number_seq START WITH 1;

CREATE TABLE IF NOT EXISTS public.store_reservations (
  id bigint generated by default as identity primary key,
  token text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','COMMITTED','EXPIRED','RELEASED')),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS public.store_reservation_items (
  id bigint generated by default as identity primary key,
  reservation_id bigint NOT NULL REFERENCES public.store_reservations(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES public.products(id),
  quantity double precision NOT NULL CHECK (quantity > 0),
  unit_price_cents bigint NOT NULL CHECK (unit_price_cents >= 0),
  UNIQUE (reservation_id, product_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS orders_store_idempotency_uq ON public.orders(store_idempotency_key) WHERE store_idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS store_reservations_active_idx ON public.store_reservations(status, expires_at);
CREATE INDEX IF NOT EXISTS store_reservation_items_product_idx ON public.store_reservation_items(product_id);
CREATE INDEX IF NOT EXISTS clients_store_phone_idx ON public.clients(store_phone_normalized);
