-- KHORA: esquema consolidado para Supabase/PostgreSQL.
-- Las fechas se conservan como texto ISO para mantener compatibilidad con los
-- datos históricos de D1 durante la migración.

create table if not exists public.price_lists (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  price_modifier double precision not null default 1 check (price_modifier > 0),
  is_default integer not null default 0 check (is_default in (0, 1)),
  active integer not null default 1 check (active in (0, 1)),
  created_at text not null default (current_timestamp::text)
);

create table if not exists public.clients (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  phone text,
  email text,
  address text,
  price_list_id integer references public.price_lists(id),
  active integer not null default 1 check (active in (0, 1)),
  created_at text not null default (current_timestamp::text)
);

create table if not exists public.suppliers (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  phone text,
  email text,
  address text,
  active integer not null default 1 check (active in (0, 1)),
  created_at text not null default (current_timestamp::text)
);

create table if not exists public.categories (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  prefix text unique,
  kind text not null check (kind in ('MATERIAL', 'PRODUCT', 'EXPENSE')),
  active integer not null default 1 check (active in (0, 1))
);

create table if not exists public.code_base (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  entity_type text not null check (entity_type in ('MATERIAL', 'PRODUCT', 'COMBO')),
  category_id integer references public.categories(id),
  manual_category text,
  manual_type text,
  description text,
  unit text,
  active integer not null default 1 check (active in (0, 1)),
  created_at text not null default (current_timestamp::text)
);

create table if not exists public.raw_materials (
  id integer generated by default as identity primary key,
  code_base_id integer not null unique references public.code_base(id),
  category_id integer references public.categories(id),
  preferred_supplier_id integer references public.suppliers(id),
  unit text not null,
  current_stock double precision not null default 0 check (current_stock >= 0),
  minimum_stock double precision not null default 0 check (minimum_stock >= 0),
  current_cost_cents bigint not null default 0 check (current_cost_cents >= 0),
  notes text,
  active integer not null default 1 check (active in (0, 1))
);

create table if not exists public.raw_material_purchases (
  id integer generated by default as identity primary key,
  operation_key text not null unique,
  material_id integer not null references public.raw_materials(id),
  supplier_id integer references public.suppliers(id),
  quantity double precision not null check (quantity > 0),
  input_quantity double precision,
  input_unit text,
  base_quantity double precision,
  total_cost_cents bigint not null check (total_cost_cents >= 0),
  unit_cost_cents bigint not null check (unit_cost_cents >= 0),
  payment_status text not null default 'PAID',
  invoice_number text,
  purchased_unit text,
  status text not null default 'CONFIRMED' check (status in ('CONFIRMED', 'CANCELLED')),
  cancelled_at text,
  purchased_at text not null default (current_timestamp::text),
  notes text
);

create table if not exists public.products (
  id integer generated by default as identity primary key,
  code_base_id integer not null unique references public.code_base(id),
  category_id integer references public.categories(id),
  type text not null check (type in ('MANUFACTURED', 'COMBO')),
  photo_url text,
  sale_price_cents bigint not null default 0 check (sale_price_cents >= 0),
  estimated_cost_cents bigint not null default 0 check (estimated_cost_cents >= 0),
  last_batch_unit_cost_cents bigint not null default 0 check (last_batch_unit_cost_cents >= 0),
  profit_percentage double precision not null default 30 check (profit_percentage >= 0),
  suggested_price_cents bigint not null default 0 check (suggested_price_cents >= 0),
  current_stock double precision not null default 0 check (current_stock >= 0),
  minimum_stock double precision not null default 0 check (minimum_stock >= 0),
  active integer not null default 1 check (active in (0, 1))
);

create table if not exists public.price_list_items (
  id integer generated by default as identity primary key,
  price_list_id integer not null references public.price_lists(id) on delete cascade,
  product_id integer not null references public.products(id) on delete cascade,
  price_cents bigint not null check (price_cents >= 0),
  created_at text not null default (current_timestamp::text),
  unique (price_list_id, product_id)
);

create table if not exists public.recipes (
  id integer generated by default as identity primary key,
  product_id integer not null unique references public.products(id),
  yield_quantity double precision not null default 1 check (yield_quantity > 0),
  active integer not null default 1 check (active in (0, 1)),
  updated_at text
);

create table if not exists public.recipe_items (
  id integer generated by default as identity primary key,
  recipe_id integer not null references public.recipes(id) on delete cascade,
  material_id integer not null references public.raw_materials(id),
  quantity_per_yield double precision not null check (quantity_per_yield > 0),
  unique (recipe_id, material_id)
);

create table if not exists public.combos (
  id integer generated by default as identity primary key,
  product_id integer not null unique references public.products(id),
  active integer not null default 1 check (active in (0, 1)),
  updated_at text
);

create table if not exists public.combo_recipe_items (
  id integer generated by default as identity primary key,
  combo_id integer not null references public.combos(id) on delete cascade,
  component_product_id integer not null references public.products(id),
  quantity double precision not null check (quantity > 0),
  unique (combo_id, component_product_id)
);

create table if not exists public.combo_material_items (
  id integer generated by default as identity primary key,
  combo_id integer not null references public.combos(id) on delete cascade,
  material_id integer not null references public.raw_materials(id),
  quantity double precision not null check (quantity > 0),
  unique (combo_id, material_id)
);

create table if not exists public.manufacturing_batches (
  id integer generated by default as identity primary key,
  operation_key text not null unique,
  batch_number text,
  product_id integer not null references public.products(id),
  quantity double precision not null check (quantity > 0),
  initial_quantity double precision,
  available_quantity double precision,
  total_cost_cents bigint not null check (total_cost_cents >= 0),
  unit_cost_cents bigint not null check (unit_cost_cents >= 0),
  manufactured_at text not null default (current_timestamp::text),
  notes text
);

create table if not exists public.manufacturing_materials (
  id integer generated by default as identity primary key,
  batch_id integer not null references public.manufacturing_batches(id) on delete cascade,
  material_id integer not null references public.raw_materials(id),
  quantity_used double precision not null check (quantity_used > 0),
  frozen_unit_cost_cents bigint not null check (frozen_unit_cost_cents >= 0),
  frozen_total_cost_cents bigint not null check (frozen_total_cost_cents >= 0)
);

create table if not exists public.combo_batches (
  id integer generated by default as identity primary key,
  operation_key text not null unique,
  batch_number text,
  combo_id integer not null references public.combos(id),
  quantity double precision not null check (quantity > 0),
  initial_quantity double precision,
  available_quantity double precision,
  total_cost_cents bigint not null check (total_cost_cents >= 0),
  unit_cost_cents bigint not null check (unit_cost_cents >= 0),
  assembled_at text not null default (current_timestamp::text),
  notes text
);

create table if not exists public.combo_batch_items (
  id integer generated by default as identity primary key,
  batch_id integer not null references public.combo_batches(id) on delete cascade,
  component_product_id integer not null references public.products(id),
  quantity_used double precision not null check (quantity_used > 0),
  frozen_unit_cost_cents bigint not null check (frozen_unit_cost_cents >= 0),
  frozen_total_cost_cents bigint not null check (frozen_total_cost_cents >= 0)
);

create table if not exists public.combo_batch_item_lot_allocations (
  id integer generated by default as identity primary key,
  combo_batch_item_id integer not null references public.combo_batch_items(id) on delete cascade,
  manufacturing_batch_id integer references public.manufacturing_batches(id),
  source_combo_batch_id integer references public.combo_batches(id),
  quantity double precision not null check (quantity > 0),
  frozen_unit_cost_cents bigint not null check (frozen_unit_cost_cents >= 0),
  frozen_total_cost_cents bigint not null check (frozen_total_cost_cents >= 0),
  check ((manufacturing_batch_id is not null)::integer + (source_combo_batch_id is not null)::integer = 1)
);

create table if not exists public.combo_batch_materials (
  id integer generated by default as identity primary key,
  batch_id integer not null references public.combo_batches(id) on delete cascade,
  material_id integer not null references public.raw_materials(id),
  quantity_used double precision not null check (quantity_used > 0),
  frozen_unit_cost_cents bigint not null check (frozen_unit_cost_cents >= 0),
  frozen_total_cost_cents bigint not null check (frozen_total_cost_cents >= 0)
);

create table if not exists public.sales (
  id integer generated by default as identity primary key,
  operation_key text not null unique,
  client_id integer references public.clients(id),
  total_cents bigint not null check (total_cents >= 0),
  total_cost_cents bigint not null check (total_cost_cents >= 0),
  profit_cents bigint not null,
  status text not null default 'PAID' check (status in ('PAID', 'PENDING', 'CANCELLED')),
  payment_status text not null default 'PENDING',
  origin text not null default 'DIRECT',
  sold_at text not null default (current_timestamp::text),
  notes text
);

create table if not exists public.sale_items (
  id integer generated by default as identity primary key,
  sale_id integer not null references public.sales(id) on delete cascade,
  product_id integer not null references public.products(id),
  source_order_item_id integer,
  quantity double precision not null check (quantity > 0),
  frozen_unit_price_cents bigint not null check (frozen_unit_price_cents >= 0),
  frozen_unit_cost_cents bigint not null check (frozen_unit_cost_cents >= 0),
  line_total_cents bigint not null check (line_total_cents >= 0),
  line_cost_cents bigint not null check (line_cost_cents >= 0)
);

create table if not exists public.sale_manual_items (
  id integer generated by default as identity primary key,
  sale_id integer not null references public.sales(id) on delete cascade,
  description text not null,
  quantity double precision not null check (quantity > 0),
  frozen_unit_price_cents bigint not null check (frozen_unit_price_cents >= 0),
  line_total_cents bigint not null check (line_total_cents >= 0),
  notes text
);

create table if not exists public.finished_stock_allocations (
  id integer generated by default as identity primary key,
  sale_item_id integer not null references public.sale_items(id) on delete cascade,
  manufacturing_batch_id integer references public.manufacturing_batches(id),
  combo_batch_id integer references public.combo_batches(id),
  quantity double precision not null check (quantity > 0),
  frozen_unit_cost_cents bigint not null check (frozen_unit_cost_cents >= 0),
  frozen_total_cost_cents bigint not null check (frozen_total_cost_cents >= 0),
  created_at text not null default (current_timestamp::text),
  check ((manufacturing_batch_id is not null)::integer + (combo_batch_id is not null)::integer = 1)
);

create table if not exists public.expenses (
  id integer generated by default as identity primary key,
  code text not null unique,
  category_id integer references public.categories(id),
  code_base_id integer references public.code_base(id),
  supplier_id integer references public.suppliers(id),
  description text not null,
  quantity double precision,
  unit_cost_cents bigint,
  amount_cents bigint not null check (amount_cents >= 0),
  payment_status text not null default 'PAID' check (payment_status in ('PAID', 'UNPAID')),
  record_status text not null default 'CONFIRMED' check (record_status in ('CONFIRMED', 'CANCELLED')),
  invoice_number text,
  raw_material_purchase_id integer references public.raw_material_purchases(id),
  incurred_at text not null default (current_timestamp::text),
  notes text
);

create table if not exists public.material_sale_items (
  id integer generated by default as identity primary key,
  sale_id integer not null references public.sales(id) on delete cascade,
  material_id integer not null references public.raw_materials(id),
  quantity double precision not null check (quantity > 0),
  frozen_unit_price_cents bigint not null check (frozen_unit_price_cents >= 0),
  frozen_unit_cost_cents bigint not null check (frozen_unit_cost_cents >= 0),
  line_total_cents bigint not null check (line_total_cents >= 0),
  line_cost_cents bigint not null check (line_cost_cents >= 0)
);

create table if not exists public.stock_movements (
  id integer generated by default as identity primary key,
  operation_key text not null,
  entity_type text not null check (entity_type in ('MATERIAL', 'PRODUCT')),
  material_id integer references public.raw_materials(id),
  product_id integer references public.products(id),
  movement_type text not null check (movement_type in ('PURCHASE', 'MANUFACTURE_INPUT', 'MANUFACTURE_OUTPUT', 'COMBO_INPUT', 'COMBO_OUTPUT', 'SALE', 'ADJUSTMENT')),
  quantity_delta double precision not null check (quantity_delta <> 0),
  balance_after double precision not null check (balance_after >= 0),
  unit_cost_cents bigint not null default 0 check (unit_cost_cents >= 0),
  reference_table text not null,
  reference_id integer not null,
  notes text,
  reversed_movement_id integer references public.stock_movements(id),
  created_at text not null default (current_timestamp::text),
  check (
    (entity_type = 'MATERIAL' and material_id is not null and product_id is null)
    or (entity_type = 'PRODUCT' and product_id is not null and material_id is null)
  )
);

create table if not exists public.monthly_profits (
  id integer generated by default as identity primary key,
  month text not null unique,
  sales_cents bigint not null default 0,
  product_cost_cents bigint not null default 0,
  expense_cents bigint not null default 0,
  profit_cents bigint not null default 0,
  calculated_at text not null default (current_timestamp::text)
);

create table if not exists public.profit_history (
  id integer generated by default as identity primary key,
  month text not null,
  sales_cents bigint not null,
  product_cost_cents bigint not null,
  expense_cents bigint not null,
  profit_cents bigint not null,
  captured_at text not null default (current_timestamp::text),
  reason text not null
);

create table if not exists public.orders (
  id integer generated by default as identity primary key,
  number text not null unique,
  client_id integer references public.clients(id),
  status text not null default 'NEW',
  payment_status text not null default 'PENDING',
  subtotal_cents bigint not null default 0,
  discount_cents bigint not null default 0,
  shipping_cents bigint not null default 0,
  total_cents bigint not null default 0,
  expected_at text,
  delivery_address text,
  notes text,
  internal_notes text,
  sale_id integer references public.sales(id),
  confirmed_at text,
  stock_consumed_at text,
  cancelled_at text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text),
  archived_at text
);

create table if not exists public.order_items (
  id integer generated by default as identity primary key,
  order_id integer not null references public.orders(id) on delete cascade,
  product_id integer references public.products(id),
  description text not null,
  customization text,
  quantity double precision not null check (quantity > 0),
  unit_price_cents bigint not null check (unit_price_cents >= 0),
  line_total_cents bigint not null check (line_total_cents >= 0),
  requires_manufacturing integer not null default 0 check (requires_manufacturing in (0, 1))
);

alter table public.sale_items
  drop constraint if exists sale_items_source_order_item_fk;
alter table public.sale_items
  add constraint sale_items_source_order_item_fk
  foreign key (source_order_item_id) references public.order_items(id);

create table if not exists public.payments (
  id integer generated by default as identity primary key,
  order_id integer references public.orders(id),
  sale_id integer references public.sales(id),
  direction text not null default 'IN' check (direction in ('IN', 'OUT')),
  method text not null,
  amount_cents bigint not null check (amount_cents >= 0),
  status text not null default 'CONFIRMED',
  paid_at text not null default (current_timestamp::text),
  reference text,
  notes text,
  cancelled_at text
);

create table if not exists public.shipments (
  id integer generated by default as identity primary key,
  order_id integer not null references public.orders(id),
  client_id integer references public.clients(id),
  status text not null default 'PENDING',
  address text not null,
  carrier text,
  tracking_code text,
  cost_cents bigint not null default 0 check (cost_cents >= 0),
  dispatched_at text,
  delivered_at text,
  notes text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create table if not exists public.delivery_notes (
  id integer generated by default as identity primary key,
  number text not null unique,
  order_id integer references public.orders(id),
  sale_id integer references public.sales(id),
  client_id integer references public.clients(id),
  issued_at text not null default (current_timestamp::text),
  status text not null default 'ISSUED',
  snapshot_json text not null,
  file_key text,
  cancelled_at text
);

create table if not exists public.sale_documents (
  id integer generated by default as identity primary key,
  sale_id integer not null references public.sales(id),
  order_id integer references public.orders(id),
  type text not null check (type in ('REMITO', 'RECEIPT')),
  storage_key text not null unique,
  filename text not null,
  version integer not null default 1,
  status text not null default 'PENDING',
  snapshot_json text,
  pdf_base64 text,
  error_message text,
  generated_by text,
  created_at text not null default (current_timestamp::text),
  generated_at text,
  unique (sale_id, type, version)
);

create table if not exists public.purchase_orders (
  id integer generated by default as identity primary key,
  number text not null unique,
  supplier_id integer references public.suppliers(id),
  status text not null default 'DRAFT',
  payment_status text not null default 'PENDING',
  total_cents bigint not null default 0,
  invoice_number text,
  purchased_at text not null default (current_timestamp::text),
  notes text,
  cancelled_at text,
  created_at text not null default (current_timestamp::text)
);

create table if not exists public.purchase_order_items (
  id integer generated by default as identity primary key,
  purchase_order_id integer not null references public.purchase_orders(id) on delete cascade,
  material_id integer not null references public.raw_materials(id),
  quantity double precision not null check (quantity > 0),
  unit text not null,
  unit_cost_cents bigint not null check (unit_cost_cents >= 0),
  line_total_cents bigint not null check (line_total_cents >= 0)
);

create table if not exists public.audit_logs (
  id integer generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id integer,
  actor_email text,
  summary text not null,
  before_json text,
  after_json text,
  created_at text not null default (current_timestamp::text)
);

create table if not exists public.app_settings (
  key text primary key,
  value_json text not null,
  updated_at text not null default (current_timestamp::text)
);

create index if not exists idx_movements_operation on public.stock_movements(operation_key);
create index if not exists idx_movements_material on public.stock_movements(material_id, created_at desc);
create index if not exists idx_movements_product on public.stock_movements(product_id, created_at desc);
create index if not exists idx_sales_date on public.sales(sold_at);
create index if not exists idx_purchases_date on public.raw_material_purchases(purchased_at);
create index if not exists idx_expenses_date on public.expenses(incurred_at);
create index if not exists idx_orders_status on public.orders(status, expected_at);
create index if not exists idx_payments_order on public.payments(order_id, paid_at);
create index if not exists idx_payments_sale on public.payments(sale_id, paid_at);
create index if not exists idx_audit_entity on public.audit_logs(entity_type, entity_id, created_at desc);

insert into public.price_lists(code, name, price_modifier, is_default)
values ('STD', 'Precio estándar', 1, 1)
on conflict (code) do nothing;

insert into public.app_settings(key, value_json)
values
  ('document_remito_prefix', '"sales-documents/remitos"'),
  ('document_receipt_prefix', '"sales-documents/comprobantes"'),
  ('document_remito_include_prices', 'false')
on conflict (key) do nothing;

-- La aplicación accede desde el servidor con DATABASE_URL. El acceso anónimo
-- directo por la API de Supabase queda cerrado al no crear políticas públicas.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'price_lists', 'clients', 'suppliers', 'categories', 'code_base',
    'raw_materials', 'raw_material_purchases', 'products', 'price_list_items',
    'recipes', 'recipe_items', 'combos', 'combo_recipe_items',
    'combo_material_items', 'manufacturing_batches', 'manufacturing_materials',
    'combo_batches', 'combo_batch_items', 'combo_batch_item_lot_allocations',
    'combo_batch_materials', 'sales', 'sale_items', 'sale_manual_items',
    'finished_stock_allocations', 'expenses', 'material_sale_items',
    'stock_movements', 'monthly_profits', 'profit_history', 'orders',
    'order_items', 'payments', 'shipments', 'delivery_notes', 'sale_documents',
    'purchase_orders', 'purchase_order_items', 'audit_logs', 'app_settings'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end $$;
