-- KHORA financial foundation: cash events, reinvestment and immutable monthly closes.
-- Existing sales, purchases and expenses are preserved. Historical COGS remains in sales.

create table if not exists public.financial_payment_events (
  id bigint generated by default as identity primary key,
  operation_key text not null unique,
  event_type text not null check (event_type in ('PURCHASE_PAYMENT', 'EXPENSE_PAYMENT')),
  raw_material_purchase_id integer references public.raw_material_purchases(id),
  expense_id integer references public.expenses(id),
  amount_cents bigint not null check (amount_cents > 0),
  paid_at text not null,
  method text,
  status text not null default 'CONFIRMED' check (status in ('CONFIRMED', 'CANCELLED')),
  notes text,
  created_by text,
  created_at text not null default (current_timestamp::text),
  check (
    (event_type = 'PURCHASE_PAYMENT' and raw_material_purchase_id is not null and expense_id is null)
    or
    (event_type = 'EXPENSE_PAYMENT' and expense_id is not null and raw_material_purchase_id is null)
  )
);

create table if not exists public.reinvestment_plans (
  id bigint generated by default as identity primary key,
  month text not null unique check (month ~ '^\\d{4}-\\d{2}$'),
  mode text not null check (mode in ('PERCENT', 'FIXED')),
  percent_value numeric(7, 3),
  fixed_amount_cents bigint,
  reserved_amount_cents bigint not null default 0 check (reserved_amount_cents >= 0),
  updated_by text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text),
  check (
    (mode = 'PERCENT' and percent_value is not null and percent_value between 0 and 100 and fixed_amount_cents is null)
    or
    (mode = 'FIXED' and fixed_amount_cents is not null and fixed_amount_cents >= 0 and percent_value is null)
  )
);

create table if not exists public.reinvestment_movements (
  id bigint generated by default as identity primary key,
  operation_key text not null unique,
  month text not null check (month ~ '^\\d{4}-\\d{2}$'),
  occurred_at text not null,
  concept text not null,
  category text not null,
  amount_cents bigint not null check (amount_cents > 0),
  raw_material_purchase_id integer references public.raw_material_purchases(id),
  expense_id integer references public.expenses(id),
  notes text,
  status text not null default 'CONFIRMED' check (status in ('CONFIRMED', 'CANCELLED')),
  created_by text,
  created_at text not null default (current_timestamp::text),
  check (raw_material_purchase_id is null or expense_id is null)
);

create table if not exists public.monthly_finance_closures (
  id bigint generated by default as identity primary key,
  month text not null unique check (month ~ '^\\d{4}-\\d{2}$'),
  sales_generated_cents bigint not null default 0,
  collected_cents bigint not null default 0,
  receivable_cents bigint not null default 0,
  purchases_cents bigint not null default 0,
  purchases_paid_cents bigint not null default 0,
  purchases_pending_cents bigint not null default 0,
  expenses_cents bigint not null default 0,
  expenses_paid_cents bigint not null default 0,
  expenses_pending_cents bigint not null default 0,
  sold_cost_cents bigint not null default 0,
  gross_profit_cents bigint not null default 0,
  net_profit_cents bigint not null default 0,
  cash_income_cents bigint not null default 0,
  cash_outgoing_cents bigint not null default 0,
  cash_result_cents bigint not null default 0,
  reinvestment_mode text check (reinvestment_mode in ('PERCENT', 'FIXED')),
  reinvestment_percent numeric(7, 3),
  reinvestment_fixed_cents bigint,
  reinvestment_reserved_cents bigint not null default 0,
  reinvested_cents bigint not null default 0,
  reinvestment_available_cents bigint not null default 0,
  available_profit_cents bigint not null default 0,
  closed_at text not null default (current_timestamp::text),
  closed_by text,
  reopened_at text,
  reopened_by text,
  status text not null default 'CLOSED' check (status in ('CLOSED', 'REOPENED')),
  snapshot_json jsonb not null default '{}'::jsonb
);

create index if not exists idx_financial_payment_events_paid_at
  on public.financial_payment_events(paid_at, status);
create index if not exists idx_financial_payment_events_purchase
  on public.financial_payment_events(raw_material_purchase_id);
create index if not exists idx_financial_payment_events_expense
  on public.financial_payment_events(expense_id);
create index if not exists idx_reinvestment_movements_month
  on public.reinvestment_movements(month, status, occurred_at);

-- Preserve the meaning of existing PAID rows by recording one historical payment.
insert into public.financial_payment_events(
  operation_key, event_type, raw_material_purchase_id, amount_cents, paid_at,
  method, status, notes, created_by
)
select
  'legacy-purchase-payment-' || rp.id,
  'PURCHASE_PAYMENT', rp.id, rp.total_cost_cents, rp.purchased_at,
  'Estado histórico', 'CONFIRMED', 'Migrado desde el estado Pagado', 'migration'
from public.raw_material_purchases rp
where rp.status = 'CONFIRMED'
  and rp.payment_status = 'PAID'
  and rp.total_cost_cents > 0
on conflict (operation_key) do nothing;

insert into public.financial_payment_events(
  operation_key, event_type, expense_id, amount_cents, paid_at,
  method, status, notes, created_by
)
select
  'legacy-expense-payment-' || e.id,
  'EXPENSE_PAYMENT', e.id, e.amount_cents, e.incurred_at,
  'Estado histórico', 'CONFIRMED', 'Migrado desde el estado Pagado', 'migration'
from public.expenses e
where e.record_status = 'CONFIRMED'
  and e.payment_status = 'PAID'
  and e.raw_material_purchase_id is null
  and e.amount_cents > 0
on conflict (operation_key) do nothing;

alter table public.financial_payment_events enable row level security;
alter table public.reinvestment_plans enable row level security;
alter table public.reinvestment_movements enable row level security;
alter table public.monthly_finance_closures enable row level security;

comment on table public.financial_payment_events is
  'Real cash payments for purchases and general expenses. Server access requires an authenticated KHORA user.';
comment on table public.monthly_finance_closures is
  'Immutable financial snapshots. Reopening is explicit and audited.';
