-- Colecciones comerciales independientes de las categorías del catálogo.
-- Un producto (incluidos los productos de tipo COMBO) puede pertenecer a varias.
CREATE TABLE IF NOT EXISTS public.collections (
  id bigint generated by default as identity primary key,
  name text NOT NULL CHECK (length(trim(name)) > 0),
  slug text NOT NULL UNIQUE CHECK (length(trim(slug)) > 0),
  description text,
  status text NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PUBLISHED')),
  visible_in_store boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 1 CHECK (sort_order >= 1),
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS collections_name_ci_uq
  ON public.collections (lower(trim(name)));

CREATE INDEX IF NOT EXISTS collections_store_order_idx
  ON public.collections (sort_order, name, id)
  WHERE status = 'PUBLISHED' AND visible_in_store = true;

CREATE TABLE IF NOT EXISTS public.collection_items (
  id bigint generated by default as identity primary key,
  collection_id bigint NOT NULL REFERENCES public.collections(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  sort_order integer NOT NULL CHECK (sort_order >= 1),
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  UNIQUE (collection_id, product_id)
);

CREATE INDEX IF NOT EXISTS collection_items_order_idx
  ON public.collection_items (collection_id, sort_order, id);
CREATE INDEX IF NOT EXISTS collection_items_product_idx
  ON public.collection_items (product_id, collection_id);

ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_items ENABLE ROW LEVEL SECURITY;

-- El navegador nunca accede directamente a estas tablas. Administración y
-- tienda pasan por las rutas de servidor existentes.
REVOKE ALL ON TABLE public.collections FROM anon, authenticated;
REVOKE ALL ON TABLE public.collection_items FROM anon, authenticated;

-- Conserva la agrupación que la tienda mostraba antes como fallback visual.
INSERT INTO public.collections(name, slug, description, status, visible_in_store, sort_order)
VALUES (
  'Colección KHORA',
  'coleccion-khora',
  'Selección original de KHORA Tienda.',
  'PUBLISHED',
  true,
  1
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.collection_items(collection_id, product_id, sort_order)
SELECT collection.id, visible_product.id,
  row_number() OVER (ORDER BY visible_product.name, visible_product.id)::integer
FROM public.collections collection
CROSS JOIN LATERAL (
  SELECT p.id, cb.name
  FROM public.products p
  JOIN public.code_base cb ON cb.id = p.code_base_id
  LEFT JOIN public.categories category ON category.id = p.category_id
  WHERE p.active = 1
    AND p.store_published = true
    AND p.sale_price_cents > 0
    AND (p.category_id IS NULL OR lower(trim(category.name)) = 'colección khora')
) visible_product
WHERE collection.slug = 'coleccion-khora'
ON CONFLICT (collection_id, product_id) DO NOTHING;

COMMENT ON TABLE public.collections IS
  'Agrupaciones comerciales ordenadas y publicables de KHORA Tienda; no reemplazan categorías.';
COMMENT ON TABLE public.collection_items IS
  'Relación muchos-a-muchos ordenada entre colecciones y productos; los combos son products.type=COMBO.';
